// <auto-generated />
namespace RoomAllocation.DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AllocateRooms : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AllocateRooms));
        
        string IMigrationMetadata.Id
        {
            get { return "201808071933577_AllocateRooms"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
